"""empty message

Revision ID: 660883729df0
Revises: 9956a242918f
Create Date: 2018-10-12 19:58:26.549468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660883729df0'
down_revision = '9956a242918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
